#define IDENTIFICATEUR 258          /* IDENTIFICATEUR  */
#define CONSTANTE 259               /* CONSTANTE  */
#define VOID 260                    /* VOID  */
#define INT 261                     /* INT  */
#define FOR 262                     /* FOR  */
#define WHILE 263                   /* WHILE  */
#define IF 264                      /* IF  */
#define ELSE 265                    /* ELSE  */
#define SWITCH 266                  /* SWITCH  */
#define CASE 267                    /* CASE  */
#define DEFAULT 268                 /* DEFAULT  */
#define BREAK 269                   /* BREAK  */
#define RETURN 270                  /* RETURN  */
#define PLUS 271                    /* PLUS  */
#define MOINS 272                   /* MOINS  */
#define MUL 273                     /* MUL  */
#define DIV 274                    /* DIV  */
#define LSHIFT 275                  /* LSHIFT  */
#define RSHIFT 276                  /* RSHIFT  */
#define BAND 277                    /* BAND  */
#define BOR 278                     /* BOR  */
#define LAND 279                    /* LAND  */
#define LOR 280                     /* LOR  */
#define LT 281                      /* LT  */
#define GT 282                      /* GT  */
#define GEQ 283                     /* GEQ  */
#define LEQ 284                    /* LEQ  */
#define EQ 285                      /* EQ  */
#define NEQ 286                     /* NEQ  */
#define NOT 287                     /* NOT  */
#define EXTERN 288                  /* EXTERN  */
#define THEN 289                    /* THEN  */
#define OP 290                     /* OP  */